steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 
      'gcr.io/$PROJECT_ID/customer-support-rag:$COMMIT_SHA',
      '-t',
      'gcr.io/$PROJECT_ID/customer-support-rag:latest',
      '.'
    ]
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/customer-support-rag:$COMMIT_SHA']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/customer-support-rag:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'customer-support-rag',
      '--image', 'gcr.io/$PROJECT_ID/customer-support-rag:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8000',
      '--memory', '4Gi',
      '--cpu', '2',
      '--max-instances', '10',
      '--timeout', '300',
      '--set-env-vars', 'PORT=8000'
    ]

images:
  - gcr.io/$PROJECT_ID/customer-support-rag:$COMMIT_SHA
  - gcr.io/$PROJECT_ID/customer-support-rag:latest 